# Generated by Django 4.2.3 on 2023-07-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=15)),
                ('url', models.URLField()),
                ('img', models.URLField()),
                ('visite_count', models.IntegerField()),
            ],
        ),
    ]
