# Generated by Django 4.2.4 on 2023-08-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9999)),
                ('country', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('img', models.CharField(max_length=9999)),
                ('visit_count', models.IntegerField(default=0)),
                ('created_at', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
