# Generated by Django 4.2.3 on 2023-07-24 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Issue',
        ),
    ]
