# Generated by Django 4.2.3 on 2023-07-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_api', '0002_rename_movie_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='visite_count',
            field=models.IntegerField(default=0),
        ),
    ]
