# Generated by Django 4.2.3 on 2023-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_api', '0005_alter_issue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateField(verbose_name='date_published'),
        ),
    ]
