# Generated by Django 4.2.3 on 2023-07-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_api', '0007_alter_issue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='img',
            field=models.CharField(max_length=999),
        ),
    ]
