# Generated by Django 4.2.3 on 2023-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_api', '0008_alter_issue_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='img',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=9999),
        ),
    ]
